### ISSUE TITLE
Search bar should be lined up visually with the mathematical header

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/DSS#355]
### Current display

The search bar begins further right than the DSS image with mathematical symbols

<img width="587" alt="the search bar is above the image, and it looks a bit odd" src="https://github.com/pulibrary/DSS/assets/7086943/91b28e68-3e17-4568-b0a8-0af8f3002611">

### Desired display

The search bar begins at the same horizontal location as the DSS image.

### Acceptance criteria

- [ ] The search bar begins at the same horizontal location as the DSS image.

**Comment by sandbergja** [comment]
@Phil94comp : thanks!  Yes, you will want to ensure that you have ruby, bundler, lando, and yarn installed, then follow those steps.  When you get to the rake task, it would be as written (`rake dss:servers:start`).  The `dss` part of that command comes from the [rake task namespace in this file](https://github.com/pulibrary/DSS/blob/main/lib/tasks/dss.rake#L3), rather than from the name of the directory.

**Comment by Phil94comp** [comment]
@sandbergja I have ruby, bundler, and yarn installed on my computer. However, as I was installing lando, when I clicked on the executable file, the Windows protection alert popped up stating it blocked the installer from running. I am not familiar with lando, but when I looked it up apparently the warning for Windows users has been popping up regarding lando for several years. Nobody seemed to have a good solution regarding how to handle it or stated if it was safe to proceed with the download. Is there a way I can work on this project without using lando? If not, I am sorry but I can't continue working on the project because I am concerned about downloading the program with that warning.

**Comment by sandbergja** [comment]
@Phil94comp -- good to know about that Windows warning, thanks for the info!  An alternative would be to not run `rake dss:servers:start`, and instead:

- Install Apache solr locally
- Edit config/blacklight.yml locally to point to your local version of solr
- Install Postgresql server locally
- Edit config/db.yml locally to point to your local version of postgresql

**Comment by Phil94comp** [comment]
@sandbergja I was working on the project and I have some questions. For the configuration on the blacklight.yml and database.yml files are the changes that I made correct for setting up Apache solr and PostgreSQL? The ones that show ORIGINAL are what the code was before the changes. The ones that show CHANGES are the pieces of code I changed to match my local environment. 

ORIGINAL: url: <%= ENV['SOLR_URL'] || "http://#{ENV["lando_dss_development_solr_conn_host"] || "127.0.0.1"}:#{ENV["lando_dss_development_solr_conn_port"] || 8983}/solr/dss-core-dev" %>

CHANGES: url: <%= ENV['SOLR_URL'] || "http://#{ENV["C:/Users/name/solr-9.2.1/bin/solr"] || "127.0.0.1"}:#{ENV["C:/Users/name/solr-9.2.1/bin/solr-8983"] || 8983}/solr/dss-core-dev" %>

ORIGINAL: host: <%= ENV["lando_dss_database_conn_host"] %>
  port: <%= ENV["lando_dss_database_conn_port"] %>
  username: <%= ENV["lando_dss_database_creds_user"] %>
  password: <%= ENV["lando_dss_database_creds_password"] %>
  database: dss_development

CHANGES: development: &development
  <<: *default
  host: <%= ENV["lando_dss_database_conn_host"] %>
  port: <%= ENV["lando_dss_database_conn_port"] %>
  username: <%= ENV["ausername"] %>
  password: <%= ENV["apassword"] %>
  database: dss_development

When I run the code to see the project do I still run foreman start? Also, should I ignore the rake steps 6-8 that come after step 5? 

I am new to helping out with Ruby projects so I am sorry if I am asking too many questions. Thank you for all your help.

**Comment by sandbergja** [comment]
@Phil94comp : thanks for asking the questions!  Thanks for sticking with this.  Lando saves us time and confusion when setting up postgres and solr locally, but it'll be totally possible to get this setup without lando -- it'll just require more time and experimentation, so thanks for your willingness on both of those.

You will still want to run the remaining rake tasks, which are responsible for setting up the databases and adding some sample data to them.  The `dss:servers:start` one is the only one that relies on lando.

For the solr config in blacklight.yml: when you start solr, are you able to go to your browser and see the solr interface at http://localhost:8983/solr?  If so, you can use the solr interface to create a new core using the configuration in solr/conf within this repo.  You would then set `url` in the configuration file to `http://localhost:8983/solr/name-of-the-core-you-made`.

For the postgres config in database.yml, it's a similar story.  Are you able to connect to the database at localhost:5432 with a particular username and password?  Does the user have the permissions to create a new database?  If so, you could use `localhost` as the host, `5432` as the port, the username and password you used.  If not, you may have to configure your local version of postgresql differently (different port, different username, etc.)

**Comment by sandbergja** [comment]
I should say, that instead of editing the configuration files, you could set the environment variables in your terminal.  So, for example, if postgres is running at port 5432, you could leave the config file intact, you could type the following command into cmd/powershell before running other commands.

```
set lando_dss_database_conn_port=5432
```

**Comment by Phil94comp** [comment]
@sandbergja I am able to start solr on my browser but I have some more questions regarding the solr part for the local configuration setup. 
![solr-screenshot](https://github.com/pulibrary/DSS/assets/89309169/a969f108-fe47-43d3-adf9-ae074296c948)
![screenshot of the solr conf folder](https://github.com/pulibrary/DSS/assets/89309169/42048e23-864c-4146-8409-62967b0aaf51)
When I create the new core, for the instanceDir part do I just use the same name as the name I create for the core? Which file do I use in the solr/conf folder for the dataDir? 

Is the example below the way I need to change the blacklight.yml file so I can follow the rest of the steps?

development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://#{ENV["localhost:8983/solr/name-of-the-core"] || "127.0.0.1"}:#{ENV["localhost:8983/solr/name-of-the-core"] || 8983}/solr/dss-core-dev" %>

Do I need to change the test part of the blacklight.yml file in order to run the project on my local machine?

I am very new to using solr. Thank you for answering my questions and explaining each step of the process.
